source ~/anaconda3/etc/profile.d/conda.sh 
conda activate model_guidance


# python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 64 --total_epochs 60 > train_COCO2014.txt

# python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-3 --layer Input --localization_loss_fn Energy --pareto --attribution_method BCos > train_COCO2014_Guided.txt

# python train.py --model_backbone bcos --dataset VOC2007 --learning_rate 1e-4 --train_batch_size 32 --total_epochs 50 --optimize_explanations --model_path models/VOC2007/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-3 --layer Input --localization_loss_fn Energy --pareto --attribution_method BCos > train_VOC2007_Guided.txt

# python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 24 --eval_batch_size 16 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-2 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points > train_COCO2014_Guiding_Points_lambda_0.01.txt
# python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 24 --eval_batch_size 16 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-3 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points > train_COCO2014_Guiding_Points_lambda_0.001.txt
# python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 24 --eval_batch_size 16 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-4 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points > train_COCO2014_Guiding_Points_lambda_0.0001.txt
 
# python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 24 --eval_batch_size 16 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 5e-4 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points > train_COCO2014_Guiding_Points_lambda_0.0005.txt
# python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 24 --eval_batch_size 16 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 5e-3 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points > train_COCO2014_Guiding_Points_lambda_0.005.txt


python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-1 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.1.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-2 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.01.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-3 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.001.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-4 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.0001.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-5 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.00001.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 5e-4 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.0005.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 5e-3 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.005.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1.0  --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points > logs/train_COCO2014_Guiding_Points_lambda_adaptivex1.0.txt


python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-1 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_0.1_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-2 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_0.01_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-3 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_0.001_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-4 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_0.0001_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-1 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.1_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-2 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.01_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-3 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.001_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-4 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.0001_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 1e-5 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.00001_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 5e-4 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.0005_similarity_threshold_0.98.txt
python train.py --model_backbone bcos --dataset COCO2014 --learning_rate 1e-4 --train_batch_size 32 --eval_batch_size 32 --total_epochs 10 --optimize_explanations --model_path models/COCO2014/bcos_standard_attrNone_loclossNone_origNone_resnet50_lr0.0001_sll1.0_layerInput/model_checkpoint_f1_best.pt --localization_loss_lambda 5e-3 --layer Input --localization_loss_fn Energy_Points --pareto --attribution_method BCos --feedback_type points --adaptive_lambda True --similarity_threshold 0.98 > logs/train_COCO2014_Guiding_Points_lambda_adaptivex0.005_similarity_threshold_0.98.txt

